/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 2 november 2018
 * Author: <Enter your name here>
 */
module.exports=(app)=>{
	const areas=require('../controllers/area.controller.js');
	app.post('/areas',areas.create);
	app.get('/areas',areas.findAll);
	app.get('/areas/:areaId',areas.findOne);
	app.put('/areas/:areaId',areas.update);
	app.delete('/areas/:areaId',areas.delete);
}
