/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 30 October 2018
 * Author: <Enter your name here>
 */
module.exports=(app)=>{
	const areass=require('../controllers/areas.controller.js');
	app.post('/areass',areass.create);
	app.get('/areass',areass.findAll);
	app.get('/areass/:areasId',areass.findOne);
	app.put('/areass/:areasId',areass.update);
	app.delete('/areass/:areasId',areass.delete);
}
