/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 5 november 2018
 * Author: <Enter your name here>
 */
module.exports=(app)=>{
	const clients=require('../controllers/ovmsd.client.controller.js');
	app.post('/clients',clients.create);
	app.get('/clients',clients.findAll);
	app.get('/clients/:clientId',clients.findOne);
	app.put('/clients/:clientId',clients.update);
	app.delete('/clients/:clientId',clients.delete);
}
