/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 1 november 2018
 * Author: <Enter your name here>
 */

const mongoose=require('mongoose');
require('mongoose-long')(mongoose);
var Int32=require('mongoose-int32');

const contractSchema=mongoose.Schema({
                                      _id:mongoose.Schema.Types.ObjectId,
                                     });

module.exports=mongoose.model('contract',contractSchema);
