/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 26Oct2018
 * Author: <Enter your name here>
 * Contents: Mongoose schema p
 */

const mongoose=require('mongoose');
const mongooseLong=require('mongoose-long');


module.exports=mongoose.model('P',pSchema);
